version: '3.9'

volumes:
  mongodb-data:
    driver: local
  mongodb-log:
    driver: local

networks:
  dev_network:
    driver: bridge

services:
  redis:
    container_name: redis
    image: redis:7.0.0-alpine3.15
    ports:
      - "6379:6379"
    networks:
      - dev_network

  mongodb:
    container_name: mongodb
    image: mongo:4.4.14
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_DATABASE: files
    depends_on:
      - redis
    networks:
      - dev_network
       
    volumes:
      - mongodb-data:/data/db
      - mongodb-log:/var/log/mongodb

  nginx_proxy:
    container_name: nginx_proxy
    build: ./nginx
    restart: unless-stopped
    ports:
      - 1333:80
    depends_on:
      - app
    networks:
      - dev_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_DSN: "mongodb://admin:password@127.0.0.1:27017/files"
      CELERY_BROKER: "redis://db-redis:6379/1"
      CELERY_BACKEND: "redis://db-redis:6379/2"
    ports:
      - "5001:5001"
    container_name: app
    depends_on:
      - mongodb
    networks:
      - dev_network

    volumes:
      - ./app:/app

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      MONGO_DSN: "mongodb://admin:password@127.0.0.1:27017/files"
      CELERY_BROKER: "redis://db-redis:6379/1"
      CELERY_BACKEND: "redis://db-redis:6379/2"
    container_name: celery
    depends_on:
      - mongodb
    networks:
      - dev_network
    volumes:
      - ./app:/app
