version: '3.9'

networks:
  dev_network:

services:

  redis:
    container_name: redis
    image: redis:7.0.0-alpine3.15
    ports:
      - "6379:6379"
    networks:
      dev_network:
        aliases:
          - db-redis

  mongo:
    container_name: mongo
    image: mongo:4.4.14
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: app
      MONGO_INITDB_ROOT_PASSWORD: 1234_secret
    depends_on:
      - redis
    networks:
      dev_network:
        aliases:
          - db-mongo

  app:
    image: alpine
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MONGO_DSN: "mongodb://app:1234_secret@db-mongo:27017/files?authSource=admin"
      CELERY_BROKER: "redis://db-redis:6379/4"
      CELERY_BACKEND: "redis:///db-redis:6379/2"

    ports:
      - "5000:5000"
    container_name: app
    depends_on:
      - mongo
    networks:
      dev_network:
        aliases:
          - flask
    volumes:
      - ./app:/app

  celery:
    image: alpine
    build:
      context: .
      dockerfile: Dockerfile.celery
    environment:
      MONGO_DSN: "mongodb://app:1234_secret@db-mongo:27017/files?authSource=admin"
      CELERY_BROKER: "redis://db-redis:6379/4"
    container_name: celery
    depends_on:
      - mongo
    networks:
      dev_network:
    volumes:
      - ./app:/app
